#Developer Service Account 

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: developer
---
# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: developer-viewer
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-viewer-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: developer # Name is case sensitive
  namespace: default
roleRef:
  kind: Role
  name: developer-viewer
  apiGroup: rbac.authorization.k8s.io


