---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::657840741348:role/olga-project-dev-secrets-sa-role"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-password
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "olga-project/dev/db-password"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: DB_PASSWORD